### ISSUE TITLE
release 0.4.0

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/threddsclient#7]
@davidcaron should we build the conda package on conda-forge?

I can first create the release (after merge #6) and build the pypi package.

**Comment by davidcaron** [comment]
Although I've never done it myself, I think it's a good idea to add it to conda-forge.

**Comment by cehbrecht** [comment]
There is now a 0.4.1 release on pypi:
https://pypi.org/project/threddsclient/

I had an issue with description formatting.

**Comment by cehbrecht** [comment]
@davidcaron I'm currently adding threddsclient to conda-forge. Can I add you to the maintainer list of the recipe?

**Comment by davidcaron** [comment]
Sure, no problem.

**Comment by cehbrecht** [comment]
@davidcaron threddsclient is now on conda-forge:
https://anaconda.org/conda-forge/threddsclient

**Comment by davidcaron** [comment]
Thank you!
